### ISSUE TITLE
version for arch linux?

### ISSUE THREAD

**Issue by Eaglerider70** [zyapguy/processhitman#4]
I already have g++ installed but the compile.sh doesnt realise because it's made for ubuntu/debian
please make a version made for arch

**Comment by ShiralynDev** [comment]
I could look in to this but im not an arch user myself so would be hard to debug, might set up a VM, you try to do it yourself otherwise. I'm guessing that you are running Arch with X11?

**Comment by omrih4** [comment]
I've created an arch version of compile.sh

clone the repo, replace compile.sh with this version and run it 👍🏼 

[Download](https://files.catbox.moe/1i4fij.sh)

**Comment by ShiralynDev** [comment]
> I've created an arch version of compile.sh
> 
> clone the repo, replace compile.sh with this version and run it 👍🏼 
> 
> [Download](https://files.catbox.moe/1i4fij.sh)

Great, any reason it could not be added with a pull request?

**Comment by omrih4** [comment]
> > I've created an arch version of compile.sh
> > clone the repo, replace compile.sh with this version and run it 👍🏼
> > [Download](https://files.catbox.moe/1i4fij.sh)
> 
> Great, any reason it could not be added with a pull request?

true, will make

**Comment by Eaglerider70** [comment]
> I've created an arch version of compile.sh
> 
> clone the repo, replace compile.sh with this version and run it 👍🏼
> 
> [Download](https://files.catbox.moe/1i4fij.sh)

**Comment by Eaglerider70** [comment]
thanks, I been on my pc in a while but thank you
